### ISSUE TITLE
启动 DouYinHackLiveRoomWatcherTest 报错

### ISSUE THREAD

**Issue by ChrisYJH** [scx567888/live-room-watcher#198]
Exception in thread "main" java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
	at com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
	at com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:178)
	at com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:169)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:529)
	at java.base/java.lang.Class.forName(Class.java:508)
	at com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:791)
	at com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:740)
	at com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:733)
	at com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2941)
	at com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:170)
	at com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:169)
	at org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:288)
	at org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:1107)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1067)
	at org.graalvm.polyglot.Engine$1.run(Engine.java:1061)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
	at org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:1061)
	at org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:143)
	at org.graalvm.polyglot.Engine.getImpl(Engine.java:367)
	at org.graalvm.polyglot.Engine$Builder.build(Engine.java:665)
	at cool.scx.live_room_watcher.util.GraalvmJSHelper.<clinit>(GraalvmJSHelper.java:8)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackHelper.parseBody(DouYinHackHelper.java:35)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomInfo.<init>(DouYinHackLiveRoomInfo.java:18)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomWatcher.getLiveRoomInfo(DouYinHackLiveRoomWatcher.java:142)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomWatcher.startWatch(DouYinHackLiveRoomWatcher.java:153)
	at cool.scx.live_room_watcher.test.DouYinHackLiveRoomWatcherTest.tes1(DouYinHackLiveRoomWatcherTest.java:43)
	at cool.scx.live_room_watcher.test.DouYinHackLiveRoomWatcherTest.main(DouYinHackLiveRoomWatcherTest.java:15)

**Comment by scx567888** [comment]
用 jdk21
